# Generated by Django 5.2.7 on 2025-12-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Rejected', 'Rejected'), ('Verified', 'Verified'), ('In-Process', 'In-Process'), ('Resolved', 'Resolved')], default='Pending', max_length=20),
        ),
    ]
