# Generated by Django 5.2.7 on 2025-12-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_report_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='id',
        ),
        migrations.AddField(
            model_name='report',
            name='rep_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
