# Generated by Django 5.2.7 on 2026-02-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_remove_roadcapturesegment_report_report_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roadcapturesegment',
            name='end_lat',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roadcapturesegment',
            name='end_lng',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roadcapturesegment',
            name='start_lat',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roadcapturesegment',
            name='start_lng',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='roadcapturesegment',
            name='polyline_points',
            field=models.TextField(),
        ),
    ]
