# Generated by Django 5.2.7 on 2026-02-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_remove_report_image_url_report_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
