# Generated by Django 5.2.7 on 2025-12-05 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_ml_confidence_report_ml_prediction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='severity',
            field=models.CharField(default='Low', max_length=20),
        ),
    ]
