# Generated by Django 5.2.7 on 2025-12-06 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_remove_report_id_report_rep_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='road_segment',
        ),
    ]
