# Generated by Django 5.2.7 on 2025-12-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_remove_report_road_segment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='rep_id',
        ),
        migrations.AddField(
            model_name='report',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='report',
            name='road_segment',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
