# Generated by Django 5.2.7 on 2025-12-06 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_remove_report_rep_id_report_id_report_road_segment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminAction',
        ),
    ]
