# Generated by Django 5.2.7 on 2025-12-06 15:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_delete_adminaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadCaptureSegment',
            fields=[
                ('report', models.OneToOneField(help_text='The Report instance this segment was generated for.', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='road_segment_data', serialize=False, to='reports.report')),
                ('polyline_points', models.TextField(help_text='Snapped coordinates as a single string (e.g., "lat1,lng1|lat2,lng2|...").')),
                ('center_lat', models.DecimalField(decimal_places=7, help_text='Latitude of the original, raw GPS central point (for audit).', max_digits=10)),
                ('center_lng', models.DecimalField(decimal_places=7, help_text='Longitude of the original, raw GPS central point (for audit).', max_digits=10)),
                ('capture_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Time the snapping operation was successfully performed.')),
            ],
            options={
                'verbose_name': 'Road Segment',
                'verbose_name_plural': 'Road Segments',
            },
        ),
        migrations.RemoveField(
            model_name='report',
            name='road_segment',
        ),
        migrations.AlterField(
            model_name='report',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='report',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='report',
            name='ml_confidence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
