# Generated by Django 5.2.7 on 2025-12-06 15:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_roadcapturesegment_remove_report_road_segment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roadcapturesegment',
            options={'verbose_name': 'Road Segment'},
        ),
        migrations.AlterField(
            model_name='roadcapturesegment',
            name='capture_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='roadcapturesegment',
            name='center_lat',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='roadcapturesegment',
            name='center_lng',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
    ]
