# Generated by Django 5.2.7 on 2026-01-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_alter_roadcapturesegment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roadcapturesegment',
            name='report',
        ),
        migrations.AddField(
            model_name='report',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='locality',
            field=models.CharField(blank=True, help_text='Area or sub-locality', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='road_name',
            field=models.CharField(blank=True, help_text='Reverse-geocoded road/street name', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='segment_id',
            field=models.IntegerField(blank=True, help_text='ID of the road segment this report belongs to', null=True),
        ),
        migrations.AddField(
            model_name='roadcapturesegment',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roadcapturesegment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='roadcapturesegment',
            name='locality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='roadcapturesegment',
            name='road_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='ml_confidence',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='YOLO confidence score (%)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='ml_prediction',
            field=models.CharField(blank=True, help_text='YOLO detected damage class (e.g., pothole, crack)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='roadcapturesegment',
            name='polyline_points',
            field=models.TextField(help_text='Snapped coordinates as a string (e.g., "lat1,lng1|lat2,lng2|...").'),
        ),
    ]
