# Generated by Django 5.2.7 on 2026-02-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_roadcapturesegment_end_lat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='image_url',
        ),
        migrations.AddField(
            model_name='report',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='report_images/'),
        ),
    ]
